// @ts-check
/**
 * API contract audit (Phase 4.5). Validates that every deterministic domain still exposes
 * the stable read-model surface the AI Platform (Phase 5) will consume. The required surface
 * per domain is the FROZEN contract — a build fails if a documented public API disappears.
 *
 * This is a pure filesystem+regex audit (no compilation), so it runs identically locally and
 * in CI. It reports, per domain, which required functions are exported and which are missing,
 * then exits non-zero if any required export is gone.
 *
 * Run: node scripts/api-audit.mjs   (add --write to refresh docs/api/public-api.md)
 */
import { readFileSync, writeFileSync, existsSync, readdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");

/**
 * The frozen contract. Each domain lists the required public functions and where they are
 * exposed: "core" = packages/core/src/<domain>, "server" = apps/web/server/<domain>. Server
 * seams (summary/signals/portfolio/search) are what Phase 5 reads; core selectors back them.
 */
const CONTRACT = {
  task: { core: ["taskCounts", "searchTasks", "filterTasks"], server: [] },
  planner: { core: [], server: ["summary"] },
  calendar: { core: ["computeAvailability", "computeFreeBusy"], server: [] },
  health: { core: [], server: ["signals", "summary"] },
  knowledge: { core: ["search"], server: ["summary", "signals", "portfolio", "statistics"] },
  resource: {
    core: [
      "searchResources",
      "buildResourcePortfolio",
      "buildForecast",
      "computeSignals",
      "buildSummary",
    ],
    server: ["portfolio", "summary", "signals"],
  },
  intelligence: {
    core: [
      "buildDashboard",
      "executiveSummary",
      "attentionItems",
      "generateReport",
      "lifePortfolio",
      "lifeAreas",
      "buildSummary",
      "computeSignals",
    ],
    server: ["dashboard", "summary", "signals", "portfolio"],
  },
  finance: { core: ["accountBalance"], server: ["summary", "signals"] },
  goal: { core: [], server: ["signals"] },
  life: { core: ["buildSummary", "computeSignals"], server: ["summary", "signals"] },
  analytics: { core: [], server: ["dashboard", "signals", "statusSignal"] },
  decision: { core: ["DECISION_RULES"], server: ["generate"] },
};

/** Collect every `export function/const NAME` and `export { a, b as c }` name from a dir's files. */
function exportedNames(dir) {
  if (!existsSync(dir)) return new Set();
  const names = new Set();
  const walk = (d) => {
    for (const entry of readdirSync(d, { withFileTypes: true })) {
      const p = join(d, entry.name);
      if (entry.isDirectory()) walk(p);
      else if (
        /\.(ts|tsx)$/.test(entry.name) &&
        !entry.name.endsWith(".test.ts") &&
        !entry.name.endsWith(".test.tsx")
      ) {
        const src = readFileSync(p, "utf8");
        for (const m of src.matchAll(
          /export\s+(?:async\s+)?(?:function|const|class)\s+([A-Za-z0-9_]+)/g,
        ))
          names.add(m[1]);
        for (const m of src.matchAll(/export\s*\{([^}]+)\}/g)) {
          for (const part of m[1].split(",")) {
            const as = part.split(/\s+as\s+/);
            const name = (as[1] ?? as[0]).replace(/\btype\b/, "").trim();
            if (name) names.add(name);
          }
        }
      }
    }
  };
  walk(dir);
  return names;
}

let missing = 0;
const rows = [];
for (const [domain, req] of Object.entries(CONTRACT)) {
  const coreNames = exportedNames(join(root, "packages/core/src", domain));
  const serverNames = exportedNames(join(root, "apps/web/server", domain));
  const check = (list, have, where) =>
    list.map((fn) => {
      const ok = have.has(fn);
      if (!ok) missing += 1;
      return { domain, where, fn, ok };
    });
  rows.push(...check(req.core, coreNames, "core"), ...check(req.server, serverNames, "server"));
}

// Console summary.
const byDomain = {};
for (const r of rows) (byDomain[r.domain] ??= []).push(r);
console.log("API contract audit\n==================");
for (const [domain, list] of Object.entries(byDomain)) {
  const ok = list.filter((r) => r.ok).length;
  console.log(
    `${ok === list.length ? "OK  " : "FAIL"} ${domain.padEnd(14)} ${ok}/${list.length} exports present`,
  );
  for (const r of list.filter((r) => !r.ok)) console.log(`       MISSING ${r.where}:${r.fn}`);
}

if (process.argv.includes("--write")) {
  const lines = [
    "# Public API Surface (frozen — Phase 4.5)",
    "",
    "Generated by `scripts/api-audit.mjs`. Each domain below exposes a stable read-model surface the AI Platform (Phase 5) consumes. Removing any of these is a breaking change and fails CI.",
    "",
    "| Domain | Layer | Export | Status |",
    "| --- | --- | --- | --- |",
  ];
  for (const r of rows)
    lines.push(`| ${r.domain} | ${r.where} | \`${r.fn}\` | ${r.ok ? "✅" : "❌ MISSING"} |`);
  writeFileSync(join(root, "docs/api/public-api.md"), lines.join("\n") + "\n");
  console.log("\nWrote docs/api/public-api.md");
}

console.log(
  `\n${missing === 0 ? "PASS" : "FAIL"}: ${rows.length - missing}/${rows.length} required exports present.`,
);
process.exit(missing === 0 ? 0 : 1);
