// @ts-check
/**
 * Dependency graph + circular-dependency audit (Phase 4.5). Builds the import graph of the
 * pure core domains (packages/core/src/<domain>) and asserts the two invariants the AI freeze
 * depends on:
 *   1. No core domain imports another core domain (each domain is self-contained; cross-domain
 *      composition happens only on the server via read models).
 *   2. No circular dependency exists between domains.
 *
 * A pure filesystem+regex audit — runs identically locally and in CI. Exits non-zero on any
 * violation. `--write` refreshes docs/architecture/dependency-graph.md.
 */
import { readFileSync, writeFileSync, readdirSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const coreSrc = join(root, "packages/core/src");

const domains = readdirSync(coreSrc, { withFileTypes: true })
  .filter((e) => e.isDirectory())
  .map((e) => e.name);

/** For each domain, the set of OTHER core domains it imports via `@myos/core/<other>`. */
const edges = {};
for (const domain of domains) {
  edges[domain] = new Set();
  const dir = join(coreSrc, domain);
  const walk = (d) => {
    for (const entry of readdirSync(d, { withFileTypes: true })) {
      const p = join(d, entry.name);
      if (entry.isDirectory()) walk(p);
      else if (/\.(ts|tsx)$/.test(entry.name) && !/\.test\.tsx?$/.test(entry.name)) {
        const src = readFileSync(p, "utf8");
        // Only real import/export-from statements — not references inside comments or strings.
        for (const m of src.matchAll(
          /(?:import|export)[^;\n]*?from\s*["']@myos\/core\/([a-z-]+)["']/g,
        )) {
          if (m[1] !== domain && domains.includes(m[1])) edges[domain].add(m[1]);
        }
        for (const m of src.matchAll(/import\s*\(\s*["']@myos\/core\/([a-z-]+)["']\s*\)/g)) {
          if (m[1] !== domain && domains.includes(m[1])) edges[domain].add(m[1]);
        }
      }
    }
  };
  if (existsSync(dir)) walk(dir);
}

// Invariant 1: no cross-domain core imports.
const crossImports = Object.entries(edges).filter(([, deps]) => deps.size > 0);

// Invariant 2: cycle detection (Tarjan-lite DFS colouring).
const WHITE = 0,
  GREY = 1,
  BLACK = 2;
const colour = Object.fromEntries(domains.map((d) => [d, WHITE]));
const cycles = [];
const stack = [];
function dfs(node) {
  colour[node] = GREY;
  stack.push(node);
  for (const next of edges[node]) {
    if (colour[next] === GREY) cycles.push([...stack.slice(stack.indexOf(next)), next]);
    else if (colour[next] === WHITE) dfs(next);
  }
  stack.pop();
  colour[node] = BLACK;
}
for (const d of domains) if (colour[d] === WHITE) dfs(d);

console.log("Dependency graph audit\n======================");
console.log(`${domains.length} core domains scanned.`);
console.log(`Cross-domain core imports: ${crossImports.length}`);
for (const [d, deps] of crossImports) console.log(`  ${d} → ${[...deps].join(", ")}`);
console.log(`Circular dependencies: ${cycles.length}`);
for (const c of cycles) console.log(`  CYCLE: ${c.join(" → ")}`);

if (process.argv.includes("--write")) {
  const lines = [
    "# Core Dependency Graph (Phase 4.5)",
    "",
    "Generated by `scripts/dependency-graph.mjs`.",
    "",
    "**Invariant:** no pure-core domain imports another pure-core domain — cross-domain composition happens only on the server via read models. This keeps every domain independently testable and lets the AI layer read one domain without pulling in the rest.",
    "",
    `- Core domains: **${domains.length}**`,
    `- Cross-domain core imports: **${crossImports.length}** ${crossImports.length === 0 ? "✅" : "❌"}`,
    `- Circular dependencies: **${cycles.length}** ${cycles.length === 0 ? "✅" : "❌"}`,
    "",
    "## Domains",
    "",
    domains.map((d) => `- \`${d}\``).join("\n"),
    "",
  ];
  if (crossImports.length) {
    lines.push("## Cross-domain imports (should be empty)", "");
    for (const [d, deps] of crossImports) lines.push(`- ${d} → ${[...deps].join(", ")}`);
  }
  writeFileSync(join(root, "docs/architecture/dependency-graph.md"), lines.join("\n") + "\n");
  console.log("\nWrote docs/architecture/dependency-graph.md");
}

const ok = crossImports.length === 0 && cycles.length === 0;
console.log(`\n${ok ? "PASS" : "FAIL"}: core domains are self-contained and acyclic.`);
process.exit(ok ? 0 : 1);
