// @ts-check
/**
 * Schema audit (Phase 4.5). Inventories every Drizzle table across packages/db/src/schema,
 * recording its owning schema file, index count and whether it carries `knowledgeNoteId`
 * (the Knowledge-link column every durable entity should support). Ledger/event/junction
 * tables are exempt by design and listed as such.
 *
 * A pure filesystem+regex audit — no DB connection needed, so it runs in CI without Postgres.
 * `--write` refreshes docs/database/schema.md.
 */
import { readFileSync, writeFileSync, readdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const schemaDir = join(root, "packages/db/src/schema");

/**
 * The `knowledgeNoteId` convention was established with the Knowledge platform (4.1). It is a
 * back-reference FROM a durable entity in a consuming domain TO a knowledge note — so the
 * requirement applies to the Knowledge-CONSUMING schema files below (Life 4.2, Resource 4.3),
 * not to Knowledge itself (its own notes are the link target, never the source). Everything in
 * earlier schema files predates the convention. Within the consuming files, ledger/event/log/
 * reference/junction rows are exempt (they are not durable entities you attach one note to).
 */
const KNOWLEDGE_ERA_FILES = new Set(["life.ts", "resource.ts"]);

/**
 * Ledger/event/log/reference rows inside the Knowledge-era files that are exempt by design —
 * time-series logs, append-only ledgers and reference catalogues are not durable entities you
 * attach a single Knowledge note to. (These omissions were made deliberately in Sprints 4.2/4.3.)
 */
const LEDGER_EXEMPT = new Set([
  // Ledgers + append-only event rows.
  "investment_transactions",
  "relationship_interactions",
  "relationship_events",
  "habit_completions",
  "routine_completions",
  "medication_logs",
  // Life (4.2): time-series logs, a junction/child row, reference catalogue and lightweight
  // tracker rows — none is a durable entity you attach a single Knowledge note to.
  "life_body_measurements",
  "workout_sessions",
  "exercise_library",
  "routine_steps",
  "medications",
  "supplements",
  "doctor_appointments",
  // Resource (4.3): a maintenance-schedule row is a dated task against an asset, not an entity.
  "asset_maintenance",
]);

const isRequiredToLink = (t) => KNOWLEDGE_ERA_FILES.has(t.file) && !LEDGER_EXEMPT.has(t.name);

const tables = [];
for (const file of readdirSync(schemaDir).filter((f) => f.endsWith(".ts") && f !== "index.ts")) {
  const src = readFileSync(join(schemaDir, file), "utf8");
  // Split by pgTable declarations so index()/column matches attribute to the right table.
  const decls = [...src.matchAll(/pgTable\(\s*["']([a-z_]+)["']/g)];
  for (let i = 0; i < decls.length; i += 1) {
    const name = decls[i][1];
    const start = decls[i].index;
    const end = i + 1 < decls.length ? decls[i + 1].index : src.length;
    const body = src.slice(start, end);
    tables.push({
      name,
      file,
      indexes: (body.match(/\bindex\(/g) || []).length,
      hasKnowledgeLink: /knowledgeNoteId/.test(body),
    });
  }
}

const withLink = tables.filter((t) => t.hasKnowledgeLink);
const missingLink = tables.filter((t) => isRequiredToLink(t) && !t.hasKnowledgeLink);
const totalIndexes = tables.reduce((s, t) => s + t.indexes, 0);

console.log("Schema audit\n============");
console.log(
  `Tables: ${tables.length} across ${new Set(tables.map((t) => t.file)).size} schema files`,
);
console.log(`Total indexes: ${totalIndexes}`);
console.log(`Tables with knowledgeNoteId: ${withLink.length}`);
console.log(`Durable tables MISSING knowledgeNoteId (not exempt): ${missingLink.length}`);
for (const t of missingLink) console.log(`  MISSING: ${t.name} (${t.file})`);

if (process.argv.includes("--write")) {
  const byFile = {};
  for (const t of tables) (byFile[t.file] ??= []).push(t);
  const lines = [
    "# Database Schema (Phase 4.5)",
    "",
    "Generated by `scripts/schema-audit.mjs`. Every table, its owning schema file, index count and whether it carries `knowledgeNoteId` (the Knowledge-link every durable entity supports; ledger/event/config tables are exempt by design).",
    "",
    `- Tables: **${tables.length}**`,
    `- Total indexes: **${totalIndexes}**`,
    `- Durable tables missing a Knowledge link (not exempt): **${missingLink.length}** ${missingLink.length === 0 ? "✅" : "❌"}`,
    "",
  ];
  for (const [file, list] of Object.entries(byFile).sort()) {
    lines.push(`## \`${file}\``, "", "| Table | Indexes | Knowledge link |", "| --- | --- | --- |");
    for (const t of list)
      lines.push(
        `| \`${t.name}\` | ${t.indexes} | ${t.hasKnowledgeLink ? "✅" : isRequiredToLink(t) ? "❌" : "— (exempt)"} |`,
      );
    lines.push("");
  }
  writeFileSync(join(root, "docs/database/schema.md"), lines.join("\n") + "\n");
  console.log("\nWrote docs/database/schema.md");
}

console.log(
  `\n${missingLink.length === 0 ? "PASS" : "FAIL"}: every durable entity supports a Knowledge link (or is exempt).`,
);
process.exit(missingLink.length === 0 ? 0 : 1);
