// @ts-check
/**
 * Security / data-classification audit (Phase 4.5). Asserts that EVERY database schema file has
 * a data-classification entry in apps/web/lib/security/classification.ts. This is the review that
 * guarantees no persisted data is unclassified before the Phase 5 AI layer can read any of it —
 * an unclassified domain could leak `private`/`sensitive` data across the AI boundary.
 *
 * Pure filesystem+regex (parses the classification module's `file:` keys) — runs in CI without
 * Postgres. `--write` refreshes docs/security/data-classification.md.
 */
import { readFileSync, writeFileSync, readdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const schemaDir = join(root, "packages/db/src/schema");
const classPath = join(root, "apps/web/lib/security/classification.ts");

const schemaFiles = readdirSync(schemaDir)
  .filter((f) => f.endsWith(".ts") && f !== "index.ts")
  .sort();

const classSrc = readFileSync(classPath, "utf8");

// Extract each classified domain block: file, level, rawAiSafe.
const entries = [
  ...classSrc.matchAll(
    /file:\s*"([^"]+)",\s*\n\s*level:\s*"([^"]+)",\s*\n\s*rawAiSafe:\s*(true|false),/g,
  ),
].map((m) => ({ file: m[1], level: m[2], rawAiSafe: m[3] === "true" }));
const classified = new Map(entries.map((e) => [e.file, e]));

const aiSafeSurfaces = [...classSrc.matchAll(/AI_SAFE_SURFACES\s*=\s*\[([^\]]+)\]/g)].flatMap((m) =>
  [...m[1].matchAll(/"([a-zA-Z]+)"/g)].map((x) => x[1]),
);

const missing = schemaFiles.filter((f) => !classified.has(f));
const orphan = entries.filter((e) => !schemaFiles.includes(e.file) && e.file !== "platform.ts");
// platform.ts holds push_subscriptions inside identity/platform schema — allow it as a valid key.

console.log("Security / data-classification audit\n====================================");
console.log(`Schema files: ${schemaFiles.length}`);
console.log(`Classified domains: ${classified.size}`);
console.log(`AI-safe surfaces declared: ${aiSafeSurfaces.length} (${aiSafeSurfaces.join(", ")})`);
console.log(`Unclassified schema files: ${missing.length}`);
for (const f of missing) console.log(`  MISSING: ${f}`);
for (const o of orphan) console.log(`  ORPHAN classification (no schema file): ${o.file}`);

if (process.argv.includes("--write")) {
  const rank = { public: 0, internal: 1, sensitive: 2, private: 3 };
  const sorted = [...entries].sort(
    (a, b) => rank[b.level] - rank[a.level] || a.file.localeCompare(b.file),
  );
  const lines = [
    "# Data Classification (Phase 4.5, Security)",
    "",
    "Generated by `scripts/security-audit.mjs` from `apps/web/lib/security/classification.ts`. Every persisted domain carries a sensitivity class, and the AI-safe boundary states what may cross to an external model in Phase 5. **There is no AI in the system today — this is the contract Phase 5 must honour.**",
    "",
    "## Levels",
    "",
    "| Level | Meaning |",
    "| --- | --- |",
    "| `public` | Non-identifying, shareable as-is (enum labels, option lists, counts). |",
    "| `internal` | Operational metadata, no personal content (ids, timestamps, statuses). |",
    "| `sensitive` | Personal but not secret — reveals habits/health/finances if disclosed. |",
    "| `private` | Secrets or free-text PII (auth tokens, email, journal/note bodies). |",
    "",
    "## AI-safe boundary",
    "",
    "Raw `sensitive`/`private` rows are **never** sent to an external model. Only the derived read models below — aggregated, scored, no free text or identifiers — are AI-safe:",
    "",
    aiSafeSurfaces.map((s) => `- \`${s}\``).join("\n"),
    "",
    "## Domain classification",
    "",
    "| Schema file | Default level | Raw rows AI-safe? |",
    "| --- | --- | --- |",
    ...sorted.map(
      (e) => `| \`${e.file}\` | \`${e.level}\` | ${e.rawAiSafe ? "✅ yes" : "❌ no"} |`,
    ),
    "",
    `All ${schemaFiles.length} schema files are classified. ${missing.length === 0 ? "✅" : "❌"}`,
    "",
  ];
  writeFileSync(join(root, "docs/security/data-classification.md"), lines.join("\n") + "\n");
  console.log("\nWrote docs/security/data-classification.md");
}

const ok = missing.length === 0 && orphan.length === 0;
console.log(`\n${ok ? "PASS" : "FAIL"}: every schema file is classified.`);
process.exit(ok ? 0 : 1);
