import type { OrchestrationModule } from "./constants";
import type { ExecutionPlan, OrchestrationConflict } from "./types";

/**
 * Conflict detection (Sprint 3.5). Deterministic checks that two in-flight or planned
 * runs don't fight over the same module (e.g. both regenerating the planner). Pure.
 */
export function detectConflicts(
  plan: ExecutionPlan,
  inFlight: ExecutionPlan[],
): OrchestrationConflict[] {
  const conflicts: OrchestrationConflict[] = [];
  const regenerating = new Set(
    plan.order.filter((s) => s.mode === "regenerate").map((s) => s.module),
  );
  for (const other of inFlight) {
    for (const step of other.order) {
      if (step.mode === "regenerate" && regenerating.has(step.module)) {
        conflicts.push({
          module: step.module,
          reason: `${step.module} is already being regenerated by the ${other.pipeline} pipeline.`,
        });
      }
    }
  }
  return conflicts;
}

/** Whether a plan can proceed given the in-flight runs (no regeneration conflicts). */
export function canProceed(plan: ExecutionPlan, inFlight: ExecutionPlan[]): boolean {
  return detectConflicts(plan, inFlight).length === 0;
}

/** Modules a plan will regenerate (vs merely refresh/record). */
export function regeneratedModules(plan: ExecutionPlan): OrchestrationModule[] {
  return plan.order.filter((s) => s.mode === "regenerate").map((s) => s.module);
}
